argparser: Fix default location of logrotate conf
The wrong default location cause error producing error log:
```
root@turris-test:~# sentinel-nikola
error: cannot stat /etc/logrotate.d/iptables: No such file or directory
Exception thrown: Command '('/usr/sbin/logrotate', '-f',
'/etc/logrotate.d/iptables')' returned non-zero exit status 1.
Exception traceback: [<FrameSummary file
/usr/lib/python3.7/site-packages/sentinel_nikola/__main__.py, line 65 in main>,
<FrameSummary file /usr/lib/python3.7/site-packages/sentinel_nikola/__main__.py,
line 94 in rotate_syslog_file>, <FrameSummary file
/usr/lib/python3.7/subprocess.py, line 411 in check_output>, <FrameSummary file
/usr/lib/python3.7/subprocess.py, line 512 in run>]
```
It was possible to avoid the error - by using `-r` option:
```
root@turris-test:~# sentinel-nikola -r /etc/logrotate.d/sentinel-nikola-iptables
.conf
```