Fix crash because of unavailable /var/log because of syslog-ng restart
Nikola restarts syslog as part of its execution. It runs logrotate that
restarts syslog-ng service. It turns out that sometimes it takes
syslog-ng some time to start again back up. Nikola immediatelly after
this tries to send log to it (about time it took to rotate log). That
fails if syslog-ng is not yet running.

Solution here is to not even restart syslog and instead just reload it.
Syslog-ng clearly can catch up on moved files and create new one. This
is also suggested approach from syslog-ng's documentation about
logrotate integration. It states that reload should be invoked but at
the same time not saying that restart should not be used.

Example crash log:
    Logrotate took 0.044638 seconds
    --- Logging error ---
    Traceback (most recent call last):
      File "/usr/lib/python3.7/logging/handlers.py", line 934, in emit
    ConnectionRefusedError: [Errno 111] Connection refused

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.7/logging/handlers.py", line 937, in emit
      File "/usr/lib/python3.7/logging/handlers.py", line 855, in _connect_unixsocket
    ConnectionRefusedError: [Errno 111] Connection refused
    Call stack:
      File "/usr/bin/nikola", line 11, in <module>
	load_entry_point('nikola==3.1.0', 'console_scripts', 'nikola')()
      File "/usr/lib/python3.7/site-packages/nikola/__main__.py", line 69, in main
    Message: 'Syslog parsing took 0.092330 seconds'
    Arguments: ()
    Syslog parsing took 0.092330 seconds
    --- Logging error ---
    Traceback (most recent call last):
      File "/usr/lib/python3.7/logging/handlers.py", line 934, in emit
    OSError: [Errno 9] Bad file descriptor

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.7/logging/handlers.py", line 937, in emit
      File "/usr/lib/python3.7/logging/handlers.py", line 855, in _connect_unixsocket
    ConnectionRefusedError: [Errno 111] Connection refused
    Call stack:
      File "/usr/bin/nikola", line 11, in <module>
	load_entry_point('nikola==3.1.0', 'console_scripts', 'nikola')()
      File "/usr/lib/python3.7/site-packages/nikola/__main__.py", line 74, in main
    Message: 'Records parsed: 120'
    Arguments: ()
    Records parsed: 120
    --- Logging error ---
    Traceback (most recent call last):
      File "/usr/lib/python3.7/logging/handlers.py", line 934, in emit
    OSError: [Errno 9] Bad file descriptor

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.7/logging/handlers.py", line 937, in emit
      File "/usr/lib/python3.7/logging/handlers.py", line 855, in _connect_unixsocket
    ConnectionRefusedError: [Errno 111] Connection refused
    Call stack:
      File "/usr/bin/nikola", line 11, in <module>
	load_entry_point('nikola==3.1.0', 'console_scripts', 'nikola')()
      File "/usr/lib/python3.7/site-packages/nikola/__main__.py", line 83, in main
      File "/usr/lib/python3.7/site-packages/nikola/__main__.py", line 111, in send_parsed
    Message: 'Sending records took 0.002729 seconds'
    Arguments: ()
    Sending records took 0.002729 seconds